<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libs\dotnet\Exchange.Trading.Domain\Exchange.Trading.Domain.csproj" />
    <ProjectReference Include="..\..\..\libs\dotnet\Exchange.Trading.Application\Exchange.Trading.Application.csproj" />
    <ProjectReference Include="..\..\..\libs\dotnet\Exchange.Trading.Infrastructure\Exchange.Trading.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\libs\contracts\dotnet\Exchange.Platform.Contracts\Exchange.Platform.Contracts.csproj" />
    <ProjectReference Include="..\..\..\apps\ledger-service\src\Exchange.Ledger.Api\Exchange.Ledger.Api.csproj" />
    <ProjectReference Include="..\..\..\apps\query-api\src\Exchange.Query.Api\Exchange.Query.Api.csproj" />
  </ItemGroup>

</Project>
