<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Exchange.Trading.Application\Exchange.Trading.Application.csproj" />
    <ProjectReference Include="..\Exchange.Trading.Domain\Exchange.Trading.Domain.csproj" />
    <ProjectReference Include="..\..\contracts\dotnet\Exchange.Platform.Contracts\Exchange.Platform.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
